function [it,population,runTime]=myGA(f,V,M,lb,ub)
% myGA(f,V,M,lb,ub)
% f : function to minimize
% V : Dimension of the search space.
% sM : Number of objectives.
% lb = lower bound vector.
% ub = upper bound vector.

%% DEFINITION OF THE PARAMETERS

% N = 32;         % Population size
% NP = round(N/2);       % Size of the mating pool
% NC = round(N);       % Number of children generated by generation
% %NC = N;
% P_start = 0.05;        % probability of recombination
% M_start = 1 - P_start;
% P_end = 0.8;
% sd_mut_start = 1;  % standard deviation of Gaussian for mutation
% sd_mut_end = 0.05;
% intervalScalar = 1.2;   % scale the parent interval to create more variation 
%                         % and not get stuck in local minimum because you always stay in between the parents

N= 16;    
P_end = 0.44;
sd_mut_end = 0.26;
NP = 9;
NC = 8;
intervalScalar = 1.35;

%0.44 | sd_mut:  0.26 | N: 10.00 | NP:  9.00 | NC:  8.00 | interval:  1.35 

verbose=1;
%% GENETIC ALGORITHM

% Generation of the intial population
population=initPopulation(N,V,M);
disp('initialPopulation')
disp(population)

population=evaluatePopulation(population,f,V,M,lb,ub);
disp('initialPopulation')
disp(population)

population=sortPopulation(population,V,M);
disp('initialPopulation')
disp(population)

% Main loop
startTime = cputime;

it=1;
stopFlag = 0;
crowdingDistanceFlag = 0;
while stopFlag==0
    
    % use this to enable/disable variable P and sd_mut.
    % Setting to crowdingDistanceFlag uses first variable, and when everything reached rank 1 fixed
    fixedPFlag = 1; %crowdingDistanceFlag;
    if fixedPFlag == 0
        sd_mut = sd_mut_start/it;
        P = 1 - (M_start/it);
    else
        P = P_end;
        sd_mut = sd_mut_end;
    end
    % For Monte Carlo
    %oldPopulationObjectives = population(:,V+1:V+M);
    
    parents=selectionTournament(population,NP,V,M);
    
    offspring=geneticOperators(parents,NC,P,intervalScalar,sd_mut,V,M,f,lb,ub);
    % new variable to prevent MATLAB from copying the whole array -> faster
    populationOffspring = [ population ; offspring ];
    
    if crowdingDistanceFlag == 0
        populationOffspring = sortPopulation(populationOffspring,V,M);
        population = cropPopulation(populationOffspring,N);
    else
        population = sortPopulationCrowding(populationOffspring,V,M,N);
    end
    
    % Visualization
    if verbose %&& mod(it,10)==0
        top20 = [normalizePopulation(population(:,1:V),lb,ub) , population(:,V+1:end)]
        illustratePopulation(population,V,M,lb,ub,it);
        drawnow;
        pause(0.05);
    end
    
    [stopFlag, crowdingDistanceFlag] = stopCriterion(it, population(:,V+M+1),population, V+M+2);%oldPopulationObjectives, population(:,V+1:V+M), notChangingLimit, V, M);
    it=it+1;
end
    
runTime = cputime - startTime;

end
        